spring:
# BANCO DE DADOS
  datasource:
    url: jdbc:mysql://localhost/recepcao?reconnect=true
    username: root
    password: root
    
# E-MAIL
  mail:
    host: smtp.gmail.com
    username: recepcao@gmail.com
    password: Recepcao*2020!
    #password: fuxpykfclldpxzdb
    properties:
      mail:
        smtp:
          auth: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
            fallback: false
          starttls:
            enable: true
          ssl:
            enable: true
# LOG
logging:
  level:
    # root: debug
    com.frazao.recepcao: trace
    org.hibernate.SQL: off
    org.springframework.web: off
    org.springframework.security: off
    org.springframework.orm: off
    org.springframework.orm.jpa: off
    org.springframework.transaction: off
    org.springframework.transaction.interceptor: off
    org.springframework.jdbc: off
  
# VALORES PADRAO
default:
# BANCO DE DADOS
  database_schema: recepcao
# E-MAIL
  sender: recepcao@gmail.com
  recipient: recepcao@gmail.com
